### ISSUE TITLE
Tailwind integration

### ISSUE THREAD

**Issue by tkroll** [tomasklaen/postcss-prune-var#1]
Can't get this working alongside TailwindCSS.

Tried this:

```typescript
const path = require('path')

module.exports = {
  plugins: {
    tailwindcss: {
      config: path.join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
    'postcss-prune-var': {},
  },
}
```

and this:

```typescript
const path = require('path')
const postcss = require('postcss')
const pruneVar = require('postcss-prune-var')

module.exports = {
  plugins: {
    tailwindcss: {
      config: path.join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
  },
}
postcss([pruneVar()])
```

Both run but unused vars remain.

Any thoughts?

**Comment by tomasklaen** [comment]
Not familiar with tailwind, haven't used it yet. If you provide a simple isolated example I can just run and check what's going on I might look into it.

**Comment by tkroll** [comment]
Here is a [StackBlitz](https://stackblitz.com/edit/daisyui-solidjs-r6r3em?file=postcss.config.js,package.json,src%2FApp.jsx,dist%2Fassets%2Findex.ea958561.css) that is similar to my setup.

I'm not sure I have your plugin setup correctly. I get the same css output when I `npm run build` with or without`'postcss-prune-var': {}` in `postcss.config`.

Thanks.

**Comment by tomasklaen** [comment]
This is an issue with your vite configuration. After adding some logging to the plugin, I've noticed that it doesn't run at all (as if it's not added to the postccs plugins array), but after a couple minutes of reading vite docs and adding this:

```js
css: {
  postcss: {
    plugins: [tailwindcss(), autoprefixer(), pruneVar()],
  },
}
```

to `vite.config.js`, it suddenly started being called and report all props it's pruning.

So I suggest studying vite docs a bit to figure out why it's not reading or working with `postcss.config.js` properly. I personally don't use vite and don't have time to dive into it to help more here.
